### ISSUE TITLE
I get ConnectionRefusedError when running train_detector.py on my lab server

### ISSUE THREAD

**Issue by bin70** [lijx10/USIP#5]
Hello jiaxin,

Thanks for your brilliant work and kindly sharing! 
I tried to run `kitti/train_detector.py` but the following error occurred. I have searched using Google for a long time but failed to find a solution. Could you please give me some help or tips?
```
------------ Options -------------
activation: relu
batch_size: 8
bn_momentum: 0.1
bn_momentum_decay: 0.6
bn_momentum_decay_step: None
checkpoints_dir: ./checkpoints
dataroot: /home/elvin/kitti
dataset: kitti
device: cuda:1
display_id: 101
display_winsize: 256
gpu_ids: [1, 0]
input_pc_num: 16384
k: 1
keypoint_on_pc_alpha: 0.01
keypoint_on_pc_type: point_to_point
keypoint_outlier_thre: 3
loss_sigma_lower_bound: 0.001
lr: 0.001
nThreads: 10
name: train
node_knn_k_1: 16
node_num: 512
normalization: batch
radius_threshold: 100
random_pc_dropout_lower_limit: 1
rot_3d: False
rot_horizontal: True
rot_perturbation: False
scene: outdoor
surface_normal_len: 4
translation_perturbation: False
-------------- End ----------------
#training point clouds = 20409
#testing point clouds = 2792
Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb56f612b00>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/101 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb56f612b00>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/elvin/anaconda3/envs/pytorch/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/101 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb56f612b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
[Errno 111] Connection refused
```

**Comment by lijx10** [comment]
That is because the visualization tool 'visdom' is not running. Please refer to https://github.com/facebookresearch/visdom    for details.

**Comment by bin70** [comment]
Thanks for your reply.  The problem is attributed to the incorrect execution order that I run `visdom` after `train_detector.py`previously. Now, it has been resolved by changing the order.

**Comment by CaineGu** [comment]
I have got the same problem, could you please tell me how to change the order when I run train_dectector.py?

**Comment by lijx10** [comment]
Simply run visdom before training.
